### ISSUE TITLE
Connect error for http://app.dataseer.ai/dataseer/documents/5e85941d8da9d17be5dce7d1

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#103]
clicking on the link for this doc gives the error message:

Connect
500 TypeError: /home/lopez/dataseer-web/views/documents/finish.pug:84
   82|         div(class='col-12')
   83|           div(class='key d-inline')
 > 84|           each val, index in document.datasets.current
   85|
   86|             div(class='row row-margin')
   87|               div(class='col-12')
Cannot read property 'length' of undefined
   at eval (eval at wrap (/home/lopez/dataseer-web/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:471:32)
   at eval (eval at wrap (/home/lopez/dataseer-web/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:658:4)
   at template (eval at wrap (/home/lopez/dataseer-web/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:975:318)
   at Object.exports.renderFile (/home/lopez/dataseer-web/node_modules/pug/lib/index.js:427:38)
   at Object.exports.renderFile (/home/lopez/dataseer-web/node_modules/pug/lib/index.js:417:21)
   at View.exports.__express [as engine] (/home/lopez/dataseer-web/node_modules/pug/lib/index.js:464:11)
   at View.render (/home/lopez/dataseer-web/node_modules/express/lib/view.js:135:8)
   at tryRender (/home/lopez/dataseer-web/node_modules/express/lib/application.js:640:10)
   at Function.render (/home/lopez/dataseer-web/node_modules/express/lib/application.js:592:3)
   at ServerResponse.render (/home/lopez/dataseer-web/node_modules/express/lib/response.js:1012:7)
   at /home/lopez/dataseer-web/routes/documents.js:50:16
   at /home/lopez/dataseer-web/node_modules/mongoose/lib/model.js:4827:16
   at /home/lopez/dataseer-web/node_modules/mongoose/lib/query.js:4390:12
   at /home/lopez/dataseer-web/node_modules/mongoose/lib/query.js:2869:28
   at processTicksAndRejections (internal/process/task_queues.js:79:11)

**Comment by timvines19** [comment]
also this one: http://app.dataseer.ai/dataseer/documents/5e8595df8da9d17be5dce7d4

**Comment by NicolasKieffer** [comment]
@kermitt2 
Document 5e8595df8da9d17be5dce7d4 seems to be not well formed : it does not have key "datasets.current".
I don't know how it happened. Could I get concerned PDF file (& its current MongoDB Object)?

**Comment by timvines19** [comment]
Yeah - it looks like the pdf is corrupted (attached as zip because the pdf won’t attach)

Tim



Tim Vines
tim.h.vines@gmail.com

This e-mail message, and any attachments, is for the sole use of the intended 
recipient(s) and may contain confidential or proprietary information that is legally privileged.
If you are not the intended recipient, please promptly contact the sender and destroy 
all copies of the original message.
