### ISSUE TITLE
Connect error for http://app.dataseer.ai/dataseer/documents/5e85b9758da9d17be5dce7e0

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#105]
I was able to 'Reopen document' and check it through. I clicked 'Finish' without making any changes and hit this error:

Connect
500 TypeError: /home/lopez/dataseer-web/views/documents/finish.pug:84
   82|         div(class='col-12')
   83|           div(class='key d-inline')
 > 84|           each val, index in document.datasets.current
   85|
   86|             div(class='row row-margin')
   87|               div(class='col-12')
Cannot read property 'length' of undefined
   at eval (eval at wrap (/home/lopez/dataseer-web/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:471:32)
   at eval (eval at wrap (/home/lopez/dataseer-web/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:658:4)
   at template (eval at wrap (/home/lopez/dataseer-web/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:975:318)
   at Object.exports.renderFile (/home/lopez/dataseer-web/node_modules/pug/lib/index.js:427:38)
   at Object.exports.renderFile (/home/lopez/dataseer-web/node_modules/pug/lib/index.js:417:21)
   at View.exports.__express [as engine] (/home/lopez/dataseer-web/node_modules/pug/lib/index.js:464:11)
   at View.render (/home/lopez/dataseer-web/node_modules/express/lib/view.js:135:8)
   at tryRender (/home/lopez/dataseer-web/node_modules/express/lib/application.js:640:10)
   at Function.render (/home/lopez/dataseer-web/node_modules/express/lib/application.js:592:3)
   at ServerResponse.render (/home/lopez/dataseer-web/node_modules/express/lib/response.js:1012:7)
   at /home/lopez/dataseer-web/routes/documents.js:50:16
   at /home/lopez/dataseer-web/node_modules/mongoose/lib/model.js:4827:16
   at /home/lopez/dataseer-web/node_modules/mongoose/lib/query.js:4390:12
   at /home/lopez/dataseer-web/node_modules/mongoose/lib/query.js:2869:28
   at processTicksAndRejections (internal/process/task_queues.js:79:11)

**Comment by timvines19** [comment]
same problem with this document:
https://app.dataseer.ai/dataseer/documents/5f640004cf1f8831ca95f261

![Screen Shot 2020-09-23 at 6 04 21 PM](https://user-images.githubusercontent.com/49563305/94089189-55525600-fdc7-11ea-9aa0-a5e81258cd56.png)
